### PR TITLE
Improved CLI, code restrukturierung and Inital support for node-gtk

### LINKED ISSUE #18: A little unclear how to use outside of the ts-for-gjs project
Thanks for making this! According to the README, cloning the repo and running `npm install` is all it takes to use this project, and sure enough, opening the examples/browser folder in VS Code does seem to work. However, I'm still a little unsure how best to use this project from another project. I'm guessing I need to do something like this, at least to start:

1. Create a npm package/project for the GJS code you're writing.
1. In package.json of that project, add ts-for-gjs as a dev dependency.

But after that, what else do I need to do? Or is there a different way I'm supposed to use this package? And what to do for GObject libraries that aren't included by default, such as Clutter and St for GNOME Extension development?

Thanks again!

### PR DESCRIPTION
**Pull request by JumpLink**
Here is inital support for `node-gtk` (I have also convert the two `gjs` examples to `note-gtk`), I know the project is called `ts-for-gjs` and not `ts-for-node-gtk` but I hope my adjustments will still be accepted (Maybe this project could get more contributors in this way and if there is no separate project where many tasks are the same).

For this I have restructured the code so that it doesn't get too confusing by increasing the complexity:
* Moved CLI specific code to `cli.ts`
* Add a new `TemplateProcessor` class to generate definitions from templates to reduce the GirModule class
* Add a new `Transformation` class to transform methods, enums, etc for the specific environment (gjs or node)
* Convert string templates to ejs templates
* Because there are now more source files, I have moved them all to `src/`
* The compiled source files now in `lib/`
* I have moved the dependencies loading to `module-loader.ts`
* I have moved the file parser to `module-loader.ts`
* I have moved the cli specific to `./src/commands/*` and `./src/config`
* All types now in `./src/types`, each type / interface in his own file
* Added `bin/bin.js`, required to use ts-for-gir as a cl tool by npm
* Added **ESLint** with the **Prettier** plugin, I tried to keep the code style (for example, there is a rule to not use simicolons).
* ESLint and Prettier are also used to validate and auto format the generated template files.
* I've changed the default output dir to `@types/` to make it easier to generate type definitions in other projects without having to specify the output path each time
* The output path now contains subfolders for `Gjs` and / or `node-gtk` (the directory name `node-gtk` is required to get typescript automatically working with `import * as gi from 'node-gtk'`)
* There is now a new option called `--build-type` which can be `"lib"` or `"types"`, `"lib"` is the default for generating types for `Gjs` and the way it was before. I added "types" for node-gtk and generates the types e.g. as you would publish them on DefinitelyTyped.
* Source maps are now also generated, which simplify debugging, Zhe IDE can now points directly to the typescript files e.g. at a breakpoint
* Updated dependencies
* Replaced [commander.js](https://github.com/tj/commander.js/) with [oclif](https://github.com/oclif/oclif) because `commander.js` was a difficult to use with multiple arguments
* Added wild card support for module names to load (e.g. Gtk*)
* Ask which module version should be used if several are found
* It can now be specified which modules should be ignored
* A config can now be created in which the cli options are available (e.g. the modules that should be ignored)
* Added new reserved keywords for functions, class names, etc
* Fixed data type errors
* Added a new list 

I've also prepared the project to publish it on npm to use it as a real cli tool, for this I have also improved the CLI arguments and updates the README (this fixes #18 and #1):

### Show general help

```bash
$ ts-for-gir --help  
Typescript .d.ts generator from GIR for gjs or node-gtk

VERSION
  ts-for-gir/1.0.0 linux-x64 node-v12.14.1

USAGE
  $ ts-for-gir [COMMAND]

COMMANDS
  generate  Generates .d.ts files from GIR for gjs or node-gtk
  help      display help for ts-for-gir
  list      Lists all available GIR modules
```

### Generate .d.ts files

```bash
$ ts-for-gir generate --help                                                                                                                                                       :(
Generates .d.ts files from GIR for gjs or node-gtk

USAGE
  $ ts-for-gir generate MODULES

ARGUMENTS
  MODULES  [default: *] GIR modules to load, e.g. 'Gio-2.0'. Accepts multiple modules

OPTIONS
  -b, --buildType=lib|types        [default for gjs: lib, default for node: types] Force the definitions generation type
  -e, --environments=gjs|node      [default: gjs,node] javascript environment
  -g, --girDirectory=girDirectory  [default: /usr/share/gir-1.0] GIR directory
  -h, --help                       show CLI help
  -i, --ignore=ignore              [default: ] modules that should be ignored
  -o, --outdir=outdir              [default: @types] directory to output to
  -p, --print                      print the output to console and create no files
  -v, --verbose                    Switch on/off the verbose mode
  --configName=configName          name of the config if you want to use a different name
  --ignoreConflicts                Do not ask for package versions if multiple versions are found
  --pretty                         prettifies the generated .d.ts files

EXAMPLES
  # Run 'ts-for-gir generate' in your gjs or node-gtk project to generate typings for your project, pass the gir modules you need for your project
  ts-for-gir generate

  # You can also use wild cards
  ts-for-gir generate Gtk*

  # If you want to parse all of your locally installed gir modules run
  ts-for-gir generate '*'

  # Generate .d.ts. files only for gjs
  ts-for-gir generate '*' -e gjs

  # Generate .d.ts. files only for node
  ts-for-gir generate '*' -e node

  # Use a special config file
  ts-for-gir generate --configName='.ts-for-gir.gtk4.rc.js

  # Generate .d.ts. files but not for Gtk-3.0 and xrandr-1.3
  ts-for-gir generate --ignore=Gtk-3.0 xrandr-1.3
```

### List available GIR modules

```bash
$ ts-for-gir list --help
Lists all available GIR modules

USAGE
  $ ts-for-gir list MODULES

ARGUMENTS
  MODULES  [default: *] GIR modules to load, e.g. 'Gio-2.0'. Accepts multiple modules

OPTIONS
  -g, --girDirectory=girDirectory  [default: /usr/share/gir-1.0] GIR directory
  -h, --help                       show CLI help
  -i, --ignore=ignore              [default: true] modules that should be ignored
  -v, --verbose                    Switch on/off the verbose mode
  --configName=configName          name of the config if you want to use a different name

EXAMPLES
  # Lists all available GIR modules in ./vala-girs/gir-1.0
  ts-for-gir list -g ./vala-girs/gir-1.0

  # Lists all available GIR modules in /usr/share/gir-1.0 but not Gtk-3.0 and xrandr-1.3
  ts-for-gir list --ignore=Gtk-3.0 xrandr-1.3
```

I have renamed the package name to `ts-for-gir` to make it clear that it's no longer just for gjs. So if you publish the package on npm that would be the name with my changes.

If more changes are necessary before my changes are accepted, please let me know.

I would like to submit more adjustments for node-gtk in the future :)

And this is what it looks like:

generate-conflicts

list

**Edit**
Added more descriptions of my changes

**Edit 2**
Again

### CODE REVIEW

**Comment by JumpLink** [comment]
With my last two commits I've removed the compiled files from the repository, should I also remove the generated types from the repository? This would this would make this PR a bit smaller (and would solve #17)

**Comment by sammydre** [comment]
> With my last two commits I've removed the compiled files from the repository, should I also remove the generated types from the repository? This would this would make this PR a bit smaller (and would solve #17)

It probably does make sense to remove the generated types, yes.

I haven't reviewed this in much detail yet but it looks like a good addition to me. Thank you.

**Comment by JumpLink** [comment]
I've touched a few more things, I'll let you know when I'm done

**Comment by JumpLink** [comment]
Okay I think I have it now, I re-edited my description above.

I have run the generator over all [vala-girs](https://github.com/nemequ/vala-girs), for that I extended the cli much more and I found many bugs such missing reserved keywords, variable names that start with a number and so on.

You can try it by your self by running `npm run build:test:girs`.

I have added the vala-girs as a submodule, so the following is necessary to run this new test:

```
git submodule init
git submodule update
```

P.S.
I'm sorry about the big PR, I will keep it smaller in the future

**Comment by JumpLink** [comment]
I found and fixed another small bug:

This was the list of the reserved function names:

```ts
export const RESERVED_VARIABLE_NAMES = [
    in: 1,
    function: 1,
    true: 1,
    false: 1,
    break: 1,
    arguments: 1,
    eval: 1,
    default: 1,
    new: 1,
    extends: 1,
    with: 1,
    var: 1,
    class: 1,
    delete: 1,
    return: 1,
}
```

if it has now been checked if a function name is reserved, the following was called

```ts
if (RESERVED_VARIABLE_NAMES[name]) {
    ...
}
```

But if `name === 'toString'` the check is true because the method `toString` exists in such objects.

So now I've converted `RESERVED_VARIABLE_NAMES` to an array and the check looks like this now:

```ts
if (RESERVED_VARIABLE_NAMES.includes(name)) {
    ...
}
```

**Comment by dan1707** [comment]
Hi @JumpLink ,

I tried to follow your installation steps from https://github.com/JumpLink/ts-for-gjs/blob/master/README.md but somehow I cannot find a **ts-for-gir** cli tool afterwards.
I use NodeJs v12.15.0 on Arch Linux.
What am I doing wrong?

**Comment by JumpLink** [comment]
> Hi @JumpLink ,
> 
> I tried to follow your installation steps from https://github.com/JumpLink/ts-for-gjs/blob/master/README.md but somehow I cannot find a **ts-for-gir** cli tool afterwards.
> I use NodeJs v12.15.0 on Arch Linux.
> What am I doing wrong?

You need to run `npm link` in the root of the project because the module is currently not published on npm but with `npm link` you can simulate this

**Comment by dan1707** [comment]
Thanks @JumpLink.
The issue was that I somehow mixed up your repo and this repo and in the end nothing worked :(
I uninstalled all installed npm packages and followed your instructions and now it works.
Thanks, again for your help!

**Comment by dan1707** [comment]
Regarding the `-g` option of the tool. Would it be possible to extend the tool to set multiple directories it should look at.
As an example, I would like to add St-1.0 which gir-file can be found at `/usr/share/gnome-shell`.
It depends on files which can be found at `/usr/lib/mutter-5`, which depend on files in `/usr/share/gir-1.0`.
Currently when I try generate the St-1.0 ts file the tool displays a lot of errors that it cannot find those dependencies as they are located in other directories.
It would be great if this would work: `ts-for-gir generate -g /usr/share/gir-1.0 -g /usr/lib/mutter-5 -g /usr/share/gnome-shell St-1.0 -e gjs`

**Comment by JumpLink** [comment]
Hi @dan1707, thank you for your Feedback and yes I will implementate this. I will have time for it in 1 or 2 weeks, I think. Maybe sooner

**Comment by JumpLink** [comment]
@dan1707 Okay, I got it :)

Tested on Ubuntu with
```
ts-for-gir generate St-1.0 -g /usr/share/gir-1.0 /usr/share/gnome-shell /usr/lib/x86_64-linux-gnu/mutter-5/ -e gjs
```

This also works
```
ts-for-gir generate St-1.0 -g /usr/share/gir-1.0 -g /usr/share/gnome-shell -g /usr/lib/x86_64-linux-gnu/mutter-5/ -e gjs
```

Can you test it?

**Comment by JumpLink** [comment]
@mmstick Looks like you are using Mac OS? If so, I need to test this on a Mac

**Comment by mmstick** [comment]
That's a negative. Pop!_OS (Ubuntu) 20.04

**Comment by JumpLink** [comment]
Wich node.js version? Installed with `apt` or `nvm`?

**Comment by mmstick** [comment]
Installed with `apt`: `10.15.2~dfsg-2ubuntu1`

**Comment by sammydre** [comment]
I haven't had time to review in detail, but I like the approach and it looks high quality. I'm happy that we fix up any issues we find later on the main branch.

**Comment by JumpLink** [comment]
Thank you very much!

**Comment by jambonmcyeah** [comment]
I have the same issue as mmstick

**Comment by JumpLink** [comment]
@mmstick, @jambonmcyeah If you still have the problem, it should be fixed now with the change from oclif to yargs in #44. However, node 16 is now required there

**Pull request merged**
