### PR TITLE
Support inline callback types

### PR DESCRIPTION
**Pull request by realh**
Some GirVariables (record fields etc) can have a <callback> child tag instead of a <type>. This change supports those instead of outputting 'any'.

### CODE REVIEW

**Comment by realh** [comment]
@JumpLink There are some conflicts between this and the gjsify fork, but I've resolved them in the gjsify branch of my fork.

**Comment by sammydre** [comment]
I've merged the earlier PR so this will need a little more work yet.

**Comment by realh** [comment]
I've merged your latest into my branches, so hopefully you can now merge this PR back to your branch with no problems.

**Review by JumpLink — APPROVED** [review]
I have tested the PR locally and it looks good for me. There are a few problems I noticed but they have nothing to do with this PR. I will open a separate issue for this.

**Pull request merged**
